// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqFLZeyhqXYEFsKL-qq0A8FQez3elIhXY',
    appId: '1:654879166775:web:08f90bd898498d45d10ab2',
    messagingSenderId: '654879166775',
    projectId: 'randomapiapp-123456',
    authDomain: 'randomapiapp-123456.firebaseapp.com',
    storageBucket: 'randomapiapp-123456.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmjUpuGAks3kbH8S_OrxAQiChlYRRpZmU',
    appId: '1:654879166775:android:b37d9f30d5841daed10ab2',
    messagingSenderId: '654879166775',
    projectId: 'randomapiapp-123456',
    storageBucket: 'randomapiapp-123456.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqe1wbtReKgblDTqHh5lvhb1OGtasShqM',
    appId: '1:654879166775:ios:819d0148bccc704cd10ab2',
    messagingSenderId: '654879166775',
    projectId: 'randomapiapp-123456',
    storageBucket: 'randomapiapp-123456.appspot.com',
    iosBundleId: 'com.example.randomapiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqe1wbtReKgblDTqHh5lvhb1OGtasShqM',
    appId: '1:654879166775:ios:8ac25f5325c3dbe9d10ab2',
    messagingSenderId: '654879166775',
    projectId: 'randomapiapp-123456',
    storageBucket: 'randomapiapp-123456.appspot.com',
    iosBundleId: 'com.example.randomapiapp.RunnerTests',
  );
}
